export const nationalities = {
  "": "All nationalities",
  "AU": "Australian",
  "BR": "Brazilian",
  "CA": "Canadian",
  "CH": "Swiss",
  "DE": "German",
  "DK": "Danish",
  "ES": "Spanish",
  "FI": "Finnish",
  "FR": "French",
  "GB": "British",
  "IE": "Irish",
  "IR": "Iranian",
  "NO": "Norwegian",
  "NL": "Dutch",
  "NZ": "New Zealander",
  "TR": "Turkish",
  "US": "American",
}